version: '3'
services:
  api:
    image: debian:buster
    volumes:
      - ./bin/:/n0stack
    command:
      - /n0stack/n0core
      - serve
      - api
      - --etcd-endpoints=etcd:2379
    ports:
      - "8080:8080"
      - "20180:20180"
    links:
      - etcd

  bff:
    image: debian:buster
    volumes:
      - ./bin/:/n0stack
    command:
      - /n0stack/n0bff
      - serve
      - bff
    ports:
      - "8000:80"
    links:
      - api

  etcd:
    image: quay.io/coreos/etcd:v3.3
    volumes:
      - ./sandbox/etcd:/etcd_data
    command:
      - /usr/local/bin/etcd
      - -name
      - etcd0
      - --data-dir
      - /etcd_data
      - -advertise-client-urls
      - http://127.0.0.1:2379,http://127.0.0.1:4001
      - -listen-client-urls
      - http://0.0.0.0:2379,http://0.0.0.0:4001
      - -initial-advertise-peer-urls
      - http://127.0.0.1:2380
      - -listen-peer-urls
      - http://0.0.0.0:2380
      - -initial-cluster-token
      - etcd-cluster-1
      - -initial-cluster
      - etcd0=http://127.0.0.1:2380
      # - -initial-cluster-state
      # - new
    ports:
      - "2379:2379"

networks:
  default:
    driver: bridge
    ipam:
      config:
      - subnet: '10.20.180.0/24'
